use crate::context::ArchContext;
use crate::llmcode::{LlmcodeFile, LlmcodeBlock};
use crate::resolve::ModuleIndex;
use serde_json::{json, Value};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Generate the declared (YAML) used-by map by inverting module-level depends_on.
///
/// For each module M that declares `depends_on: [A, B]`, adds M to the
/// used_by list of A and B. IDs use the full "container/module" form.
///
/// This is derived from authored YAML only — no source scanning required.
/// ASSUMPTION: module-level depends_on uses "container/module" IDs exclusively.
/// IF INVALID: add container-level dep expansion (e.g. "context" → "context/context").
pub fn generate_used_by(ctx: &ArchContext) -> HashMap<String, Vec<String>> {
    let mut used_by: HashMap<String, Vec<String>> = HashMap::new();

    for container in &ctx.arch.containers {
        let detail = match ctx.details.get(&container.id) {
            Some(d) => d,
            None => continue,
        };

        for module in &detail.modules {
            let full_id = format!("{}/{}", container.id, module.id);
            for dep in &module.depends_on {
                used_by.entry(dep.clone()).or_default().push(full_id.clone());
            }
        }
    }

    // Sort each list for deterministic output
    for list in used_by.values_mut() {
        list.sort();
    }

    used_by
}

/// Compile the arch.index.json payload from the loaded ArchContext.
///
/// Emits: {system, containers, modules, rules, stories}
/// This is the canonical structured representation of system.arch for
/// machine consumption — normalises field names and adds computed fields.
pub fn build_arch_index(ctx: &ArchContext) -> Value {
    let containers: Vec<Value> = ctx.arch.containers.iter().map(|c| {
        let modules: Vec<Value> = ctx.details.get(&c.id)
            .map(|d| d.modules.iter().map(|m| {
                json!({
                    "id": format!("{}/{}", c.id, m.id),
                    "file": m.file,
                    "files": m.files,
                    "owns": m.owns,
                    "boundary": m.boundary,
                    "depends_on": m.depends_on,
                })
            }).collect())
            .unwrap_or_default();

        json!({
            "id": c.id,
            "path": c.path,
            "description": c.description,
            "depends_on": c.depends_on,
            "modules": modules,
        })
    }).collect();

    let rules: Vec<Value> = ctx.arch.rules.iter().map(|r| {
        json!({
            "id": r.id,
            "type": r.rule_type,
            "reason": r.reason,
        })
    }).collect();

    let stories = ctx.load_stories().ok().flatten().map(|s| {
        s.stories.iter().map(|f| {
            json!({
                "id": f.id,
                "description": f.description,
                "flow": f.flow,
            })
        }).collect::<Vec<_>>()
    }).unwrap_or_default();

    json!({
        "system": {
            "name": ctx.arch.system.name,
            "description": ctx.arch.system.description,
        },
        "containers": containers,
        "rules": rules,
        "stories": stories,
    })
}

/// Compile the llmcode.index.json payload from parsed .llmcode files.
///
/// Emits: {generated_at, files: [{source, blocks: [{file, mod_id, source_hash, used_by}]}]}
///
/// `source_hash`: SHA-256 of the source file's content (first 8 hex chars).
/// `used_by` is generated by inverting the dep graph — NOT from authored USED-BY.
pub fn build_llmcode_index(
    ctx: &ArchContext,
    files: &[LlmcodeFile],
    _index: &ModuleIndex,
) -> Value {
    let used_by = generate_used_by(ctx);

    let file_entries: Vec<Value> = files.iter().map(|f| {
        let blocks: Vec<Value> = f.blocks.iter().map(|b| {
            let consumers = b.mod_id.as_ref()
                .and_then(|id| used_by.get(id))
                .cloned()
                .unwrap_or_default();
            let hash = source_hash_for_block(b, &ctx.root);

            json!({
                "file": b.file,
                "mod_id": b.mod_id,
                "source_hash": hash,
                "used_by": consumers,
            })
        }).collect();

        json!({
            "source": f.path,
            "blocks": blocks,
        })
    }).collect();

    json!({
        "generated_at": chrono_timestamp(),
        "files": file_entries,
    })
}

/// Best-effort timestamp without pulling in chrono. Returns ISO-like string.
fn chrono_timestamp() -> String {
    // ASSUMPTION: std::time only gives UNIX epoch; formatting is manual.
    // IF INVALID: add chrono dependency.
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format!("{secs}")
}

/// Compute the SHA-256 hash of a source file, returning the first 8 hex chars.
/// Returns `None` if the file cannot be read (deleted or path unknown).
///
/// ASSUMPTION: `block.file` is a path relative to `root`. IF INVALID: try
/// resolving relative to the .llmcode file's directory as a fallback.
fn source_hash_for_block(block: &LlmcodeBlock, root: &Path) -> Option<String> {
    let path = root.join(&block.file);
    let content = std::fs::read(&path).ok()?;
    Some(content_hash_short(&content))
}

/// Compute first 8 hex chars of a stable FNV-1a 64-bit hash of `data`.
///
/// FNV-1a is used instead of std's DefaultHasher — DefaultHasher's output
/// is not guaranteed stable across Rust versions, which would cause staleness
/// detection to silently break on toolchain upgrade.
fn content_hash_short(data: &[u8]) -> String {
    // FNV-1a 64-bit — deterministic, no external crate required.
    const FNV_OFFSET: u64 = 14695981039346656037;
    const FNV_PRIME: u64 = 1099511628211;
    let mut hash = FNV_OFFSET;
    for &byte in data {
        hash ^= byte as u64;
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    format!("{:016x}", hash)[..8].to_string()
}

/// Check whether the compiled index files are fresh relative to system.arch.
///
/// Returns false when either index file is missing OR when system.arch
/// has been modified more recently than arch.index.json.
/// ASSUMPTION: mtime comparison is sufficient for freshness. IF INVALID: add
/// content-hash comparison.
pub fn is_index_fresh(root: &Path) -> bool {
    let index_path = root.join("architecture").join("generated").join("arch.index.json");
    let arch_path = root.join("architecture").join("arch").join("system.arch");

    let index_mtime = std::fs::metadata(&index_path)
        .and_then(|m| m.modified())
        .ok();
    let arch_mtime = std::fs::metadata(&arch_path)
        .and_then(|m| m.modified())
        .ok();

    match (index_mtime, arch_mtime) {
        (Some(idx), Some(arch)) => idx >= arch,
        _ => false,
    }
}

/// Represents a source file that a .llmcode block describes but that has drifted
/// from its last-indexed state.
pub struct StaleBlock {
    /// Path to the .llmcode file containing the stale block.
    pub llmcode_path: PathBuf,
    /// The FILE: value from the stale block.
    pub file: String,
    /// Human-readable reason for staleness.
    pub reason: String,
}

/// Check all .llmcode blocks for staleness relative to their source files.
///
/// A block is stale when its source file no longer exists (deleted) or when
/// the source file's current hash differs from the hash stored in the last
/// compiled index.
///
/// ASSUMPTION: staleness is detected by content hash, not mtime — mtime is
/// unreliable on networked filesystems. IF INVALID: add mtime fallback.
pub fn check_llmcode_staleness(ctx: &ArchContext, files: &[LlmcodeFile]) -> Vec<StaleBlock> {
    let root = &ctx.root;
    // Build stem → full_path map from arch context so bare filenames like
    // "mod.rs" can be resolved to their actual location (e.g. "src/commands/mod.rs").
    let stem_map = build_stem_path_map(ctx);

    // Load stored hashes from compiled index (best-effort — if missing, all unknown)
    let stored_hashes = load_stored_hashes(root);

    let mut stale = Vec::new();
    for llmcode_file in files {
        for block in &llmcode_file.blocks {
            // Resolve source path: try root-relative first, fall back to stem map.
            let source_path = {
                let direct = root.join(&block.file);
                if direct.exists() {
                    direct
                } else if let Some(p) = stem_map.get(block.file.as_str()) {
                    p.clone()
                } else {
                    stale.push(StaleBlock {
                        llmcode_path: llmcode_file.path.clone(),
                        file: block.file.clone(),
                        reason: "source file no longer exists".to_string(),
                    });
                    continue;
                }
            };

            // Compare current hash to stored hash
            if let Some(stored) = stored_hashes.get(&block.file) {
                if let Ok(content) = std::fs::read(&source_path) {
                    let current = content_hash_short(&content);
                    if &current != stored {
                        stale.push(StaleBlock {
                            llmcode_path: llmcode_file.path.clone(),
                            file: block.file.clone(),
                            reason: format!(
                                "source changed since last index (stored: {stored}, current: {current})"
                            ),
                        });
                    }
                }
            }
            // No stored hash → not stale (we don't know the baseline)
        }
    }

    stale
}

/// Build a map from file stem (e.g. "mod.rs") to its full path on disk,
/// using the arch containers. Covers all modules declared in the architecture.
///
/// ASSUMPTION: file stems are unique across containers. IF INVALID (ambiguous
/// stems across containers): prefer the first match — callers should use full
/// root-relative paths in FILE: to avoid ambiguity.
fn build_stem_path_map(ctx: &ArchContext) -> HashMap<String, PathBuf> {
    let mut map = HashMap::new();
    for container in &ctx.arch.containers {
        if let Some(detail) = ctx.details.get(&container.id) {
            for module in &detail.modules {
                for file in module.all_files() {
                    let full = ctx.root.join(&container.path).join(file);
                    map.insert(file.to_string(), full);
                }
            }
        }
    }
    map
}

/// Load {file → source_hash} from the compiled llmcode.index.json.
/// Returns an empty map if the index is missing or malformed.
fn load_stored_hashes(root: &Path) -> HashMap<String, String> {
    let index_path = root
        .join("architecture")
        .join("generated")
        .join("llmcode.index.json");
    let content = match std::fs::read_to_string(&index_path) {
        Ok(c) => c,
        Err(_) => return HashMap::new(),
    };
    let val: Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(_) => return HashMap::new(),
    };

    let mut map = HashMap::new();
    if let Some(files) = val["files"].as_array() {
        for file_entry in files {
            if let Some(blocks) = file_entry["blocks"].as_array() {
                for block in blocks {
                    if let (Some(file), Some(hash)) = (
                        block["file"].as_str(),
                        block["source_hash"].as_str(),
                    ) {
                        map.insert(file.to_string(), hash.to_string());
                    }
                }
            }
        }
    }
    map
}

/// Context pack — the minimal set of architectural context needed to reason about
/// a specific file, computed on demand.
pub struct ContextPack {
    /// The target file (as provided by the caller).
    pub target_file: String,
    /// The arch module that owns the file, if found.
    pub owner_module: Option<String>,
    /// The module's declared boundary, if any.
    pub boundary: Option<String>,
    /// Arch modules this module depends on.
    pub depends_on: Vec<String>,
    /// Arch modules that depend on this module (generated used-by).
    pub used_by: Vec<String>,
    /// .llmcode blocks associated with the owner module.
    pub llmcode_blocks: Vec<LlmcodeBlockSummary>,
    /// Related modules from the same container (peers).
    pub peer_modules: Vec<String>,
}

/// A compact summary of a .llmcode block for inclusion in a ContextPack.
pub struct LlmcodeBlockSummary {
    pub file: String,
    pub mod_id: Option<String>,
    pub role: Option<String>,
    pub inv: Vec<String>,
    pub cntr_count: usize,
}

/// Build a context pack for a target file.
///
/// Resolves the owning module from the architecture .arch files, collects declared
/// dependencies, inverts the dep graph for used-by, and attaches matching
/// .llmcode blocks.
pub fn build_context_pack(
    ctx: &ArchContext,
    files: &[LlmcodeFile],
    target: &Path,
) -> ContextPack {
    // Normalise target to a relative path for matching
    let target_str = target
        .to_str()
        .unwrap_or("")
        .replace('\\', "/");

    // Find the owning module by scanning container file declarations
    let mut owner_module: Option<String> = None;
    let mut boundary: Option<String> = None;
    let mut depends_on: Vec<String> = Vec::new();
    let mut peer_modules: Vec<String> = Vec::new();

    'outer: for container in &ctx.arch.containers {
        let detail = match ctx.details.get(&container.id) {
            Some(d) => d,
            None => continue,
        };
        for module in &detail.modules {
            let module_files: Vec<String> = module.all_files()
                .iter()
                .map(|f| format!("{}/{}", container.path, f).replace('\\', "/"))
                .collect();
            let matches = module_files.iter().any(|f| {
                target_str.ends_with(f.as_str()) || f.ends_with(target_str.as_str())
            });
            if matches {
                owner_module = Some(format!("{}/{}", container.id, module.id));
                boundary = module.boundary.clone();
                depends_on = module.depends_on.clone();
                // Collect peers (other modules in the same container)
                peer_modules = detail.modules.iter()
                    .filter(|m| m.id != module.id)
                    .map(|m| format!("{}/{}", container.id, m.id))
                    .collect();
                break 'outer;
            }
        }
    }

    // Generate used-by from YAML declared deps
    let used_by_map = generate_used_by(ctx);
    let used_by = owner_module.as_ref()
        .and_then(|id| used_by_map.get(id))
        .cloned()
        .unwrap_or_default();

    // Collect matching .llmcode blocks
    let llmcode_blocks = files.iter()
        .flat_map(|f| &f.blocks)
        .filter(|b| {
            b.mod_id.as_ref() == owner_module.as_ref()
                || target_str.ends_with(&b.file)
                || b.file.ends_with(target_str.as_str())
        })
        .map(|b| LlmcodeBlockSummary {
            file: b.file.clone(),
            mod_id: b.mod_id.clone(),
            role: b.role.clone(),
            inv: b.inv.clone(),
            cntr_count: b.cntr.len(),
        })
        .collect();

    ContextPack {
        target_file: target_str,
        owner_module,
        boundary,
        depends_on,
        used_by,
        llmcode_blocks,
        peer_modules,
    }
}
